import {resolveCase,digest} from '../../tools/eval/inputs.ts';
import {compileHandoff} from '../../scripts/v0/optimizer/handoff.ts';
import {productionBudget} from '../../scripts/v0/optimizer/production_budget.ts';
import {writeFileSync,mkdirSync} from 'node:fs';
const song='amour_de_ma_vie_44s',seed=303;
const {spec,music}=await resolveCase({id:`${song}~${seed}`,song,seed,perturbation:null},-15);
const cp=compileHandoff(spec,seed,{budget:productionBudget(spec.duration),creative:{},impactContract:'line.strike.v3',phraseBoundaries:music.phases.map((p:any)=>p.t0??p.t??p.start).filter(Number.isFinite)});
const r=cp.repertoire!;
mkdirSync('generated/quality-beam',{recursive:true});writeFileSync('generated/quality-beam/amour303.json',JSON.stringify({valid:r.valid,track:digest(cp.track),failure:r.result.failure,decisions:r.result.planningDecisions,rows:r.result.rows,constructionFailure:r.constructionFailure,requests:r.plan.requests,interruptions:r.result.budgetInterruptions}));
console.log(JSON.stringify({valid:r.valid,track:digest(cp.track),failure:r.result.failure,rows:r.result.rows.length,interruptions:r.result.budgetInterruptions,work:r.physicalFrames,tail:r.result.planningDecisions.slice(-5)}));
