/**
 * "Shelter" (Porter Robinson & Madeon) — first 1:21 (81s). The fully
 * analysis-driven spec: NO elevation; the vertical lead is `amplitude` (arc
 * pop height), and every landing carries an authored `impact` (felt redirect)
 * affine-migrated from the pre-redirArc ensemble drum-hit weight.
 *
 * ═══ How the grid was built (both detectors agree) ═══
 * Run on beats/shelter_81s.mp3:
 *   • madmom (beats/shelter81_madmom.py): DBN beats → LOCKED 100.00 BPM, 4/4,
 *     median IBI 600.0 ms in every 8 s window, anchor 0.33 s, 34 bars. Downbeats
 *     every 2.4 s → 4-bar phrases at 0.33/9.93/19.53/29.13/38.73/48.33/57.93/
 *     67.53/77.13. Onset-activation energy contour (1 s buckets).
 *   • v7-consensus ENSEMBLE (beats/shelter81_ensemble.py): demucs drums stem →
 *     5 voting streams (rnn_drums, stem_drums, band_kick, band_snare, band_hat),
 *     min 3 votes, snapped to the 1/16-beat grid → 206 consensus hits. Their
 *     per-beat vote weight is the impact proxy (a 9–14-vote beat = a real drum
 *     slam → a hard landing). See beats/shelter81/{madmom,ensemble,beat_table,
 *     grid}.json.
 *
 * The CONTACT GRID is a variable-density slice of the madmom beat grid (111 of
 * the 135 beats): dense (every beat, 0.6 s) through the rhythmic sections;
 * sparse where the music breathes — 1.2 s intro/outro/breakdown, and 1.8 s
 * "float" showpiece gaps at the chorus-1 vocal thin-spot (39.33→41.13) and the
 * drop-2 mini-break (72.34→74.11→75.94). Contact density is the main
 * interestingness lever (a uniform grid rides as a flat glide); the sparse gaps
 * are where the rider soars. (The breakdown uses gentle 1.2 s bobs, not big
 * airs: a 1.8 s float lands in a hard catch, which fights the ambient feel.)
 *
 * ═══ Structure ↔ motion (no elevation) ═══
 *   INTRO   0.3–9.9   sparse 1.2 s, soft        gentle bounces, low energy
 *   GROOVE  9.9–19.5  dense 0.6 s, accents       rhythm enters (16.53 = 13-vote hit)
 *   VERSE   19.5–29.1 dense 0.6 s                steady (27.93 = 14-vote peak)
 *   BUILD   29.1–38.7 dense, impact ramps        banking speed into the chorus
 *   CHORUS1 38.7–48.3 FLOAT then dense           1.8 s air under the vocal thin-spot
 *   CHORUS2 48.3–57.9 dense + HARD impacts       the climax (many 9+ vote slams)
 *   BREAKDN 57.9–67.5 sparse 1.2 s, calm bobs    ambient breakdown (energy dip 0.037 @61 s)
 *   DROP2   67.5–77.1 dense → FLOAT → re-entry    2nd drop, mini-break, hard re-entry
 *   OUTRO   77.1–81   sparse 1.2 s, easing        gentle close
 *
 * Axes: air, speed, amplitude (no elevation — amplitude is the sole vertical
 * lead; both write the launch angle). amplitude is authored HIGH only on the
 * long sparse gaps (where a pop is physically possible) and near the dense-beat
 * cap (~0.1) through the 0.6 s grooves, so it never fights a gap it can't fill.
 * impact is the per-beat adjective (hard where the ensemble slammed, soft in
 * the floats). jitter 0 — the curves + grid carry all the variation.
 */
import type { Spec } from "../types.ts";
import { keyframes } from "../core/curves.ts";
import { beats } from "../core/beats.ts";
import { SHELTER_81_MUSIC } from "./_music.ts";

// Variable-density slice of the 100 BPM grid (111 contacts); impact is the
// per-beat felt-redirect, affine-migrated from the pre-redirArc ensemble
// on-beat vote weight (old 0.10 soft float → new 0.0000, old 0.62 climax slam
// → new 0.5250). Generated by beats/shelter81_grid.py.
const contacts = beats([
  { t: 0.33, impact: 0.0000 }, { t: 1.54, impact: 0.0000 }, { t: 2.73, impact: 0.0000 }, { t: 3.93, impact: 0.0000 },
  { t: 5.14, impact: 0.0000 }, { t: 6.34, impact: 0.0000 }, { t: 7.53, impact: 0.0000 }, { t: 8.73, impact: 0.0000 },
  { t: 9.33, impact: 0.0000 }, { t: 9.93, impact: 0.0750 }, { t: 10.53, impact: 0.0000 }, { t: 11.13, impact: 0.0000 },
  { t: 11.73, impact: 0.0000 }, { t: 12.33, impact: 0.0750 }, { t: 12.93, impact: 0.0000 }, { t: 13.53, impact: 0.4750 },
  { t: 14.13, impact: 0.0000 }, { t: 14.73, impact: 0.0750 }, { t: 15.33, impact: 0.0000 }, { t: 15.94, impact: 0.4750 },
  { t: 16.53, impact: 0.4750 }, { t: 17.13, impact: 0.0750 }, { t: 17.73, impact: 0.0000 }, { t: 18.33, impact: 0.0000 },
  { t: 18.93, impact: 0.4750 }, { t: 19.53, impact: 0.0750 }, { t: 20.13, impact: 0.0000 }, { t: 20.73, impact: 0.0000 },
  { t: 21.33, impact: 0.0000 }, { t: 21.93, impact: 0.0750 }, { t: 22.53, impact: 0.0000 }, { t: 23.13, impact: 0.0000 },
  { t: 23.73, impact: 0.0000 }, { t: 24.33, impact: 0.0750 }, { t: 24.93, impact: 0.3500 }, { t: 25.53, impact: 0.0000 },
  { t: 26.13, impact: 0.0000 }, { t: 26.73, impact: 0.0750 }, { t: 27.33, impact: 0.0000 }, { t: 27.93, impact: 0.5000 },
  { t: 28.53, impact: 0.0000 }, { t: 29.13, impact: 0.0750 }, { t: 29.73, impact: 0.0125 }, { t: 30.33, impact: 0.0375 },
  { t: 30.93, impact: 0.0500 }, { t: 31.53, impact: 0.1375 }, { t: 32.13, impact: 0.0875 }, { t: 32.73, impact: 0.4000 },
  { t: 33.33, impact: 0.1125 }, { t: 33.93, impact: 0.2125 }, { t: 34.53, impact: 0.1500 }, { t: 35.13, impact: 0.1625 },
  { t: 35.73, impact: 0.1875 }, { t: 36.33, impact: 0.2750 }, { t: 36.93, impact: 0.2125 }, { t: 37.53, impact: 0.2375 },
  { t: 38.12, impact: 0.2500 }, { t: 38.73, impact: 0.2500 }, { t: 39.33, impact: 0.1750 }, { t: 41.13, impact: 0.0000 },
  { t: 41.73, impact: 0.0250 }, { t: 42.34, impact: 0.0250 }, { t: 42.93, impact: 0.0250 }, { t: 43.53, impact: 0.1000 },
  { t: 44.13, impact: 0.0250 }, { t: 44.74, impact: 0.0250 }, { t: 45.33, impact: 0.4375 }, { t: 45.93, impact: 0.1000 },
  { t: 46.53, impact: 0.0250 }, { t: 47.13, impact: 0.0250 }, { t: 47.73, impact: 0.0250 }, { t: 48.33, impact: 0.5250 },
  { t: 48.93, impact: 0.1250 }, { t: 49.53, impact: 0.5250 }, { t: 50.13, impact: 0.1250 }, { t: 50.73, impact: 0.5250 },
  { t: 51.33, impact: 0.1250 }, { t: 51.93, impact: 0.5250 }, { t: 52.53, impact: 0.1250 }, { t: 53.13, impact: 0.2000 },
  { t: 53.73, impact: 0.5250 }, { t: 54.33, impact: 0.5250 }, { t: 54.93, impact: 0.1250 }, { t: 55.53, impact: 0.2000 },
  { t: 56.13, impact: 0.1250 }, { t: 56.73, impact: 0.5250 }, { t: 57.33, impact: 0.5250 }, { t: 57.93, impact: 0.0000 },
  { t: 59.14, impact: 0.0000 }, { t: 60.33, impact: 0.0000 }, { t: 61.54, impact: 0.0000 }, { t: 62.75, impact: 0.0000 },
  { t: 63.93, impact: 0.0000 }, { t: 65.13, impact: 0.0000 }, { t: 66.34, impact: 0.0500 }, { t: 67.53, impact: 0.2500 },
  { t: 68.13, impact: 0.4750 }, { t: 68.73, impact: 0.4750 },
  { t: 69.33, impact: 0.4750 }, { t: 69.94, impact: 0.2500 }, { t: 70.53, impact: 0.1750 }, { t: 71.14, impact: 0.1750 },
  { t: 71.73, impact: 0.4750 }, { t: 72.34, impact: 0.1250 }, { t: 74.11, impact: 0.0000 }, { t: 75.94, impact: 0.0000 },
  { t: 76.53, impact: 0.4375 }, { t: 77.13, impact: 0.0250 }, { t: 78.33, impact: 0.0250 }, { t: 79.53, impact: 0.0250 },
  { t: 80.73, impact: 0.0250 },
]);

/** Overlay metadata (title/artist/tempo + soft energy phases) for make_overlay_data.ts. */
export const overlayMeta = {
  title: "SHELTER",
  artist: "PORTER ROBINSON & MADEON",
  tempo: "100 BPM · 4/4 · air/speed/amplitude + impact",
  phases: [
    { name: "INTRO",   t0: 0.33,  t1: 9.93,  color: "#5b8def" },
    { name: "GROOVE",  t0: 9.93,  t1: 19.53, color: "#3fb6a8" },
    { name: "VERSE",   t0: 19.53, t1: 29.13, color: "#6c8cf2" },
    { name: "BUILD",   t0: 29.13, t1: 38.73, color: "#f2b134" },
    { name: "CHORUS1", t0: 38.73, t1: 48.33, color: "#f24f4f" },
    { name: "CHORUS2", t0: 48.33, t1: 57.93, color: "#e0244a" },
    { name: "BREAKDN", t0: 57.93, t1: 67.53, color: "#a06cf2" },
    { name: "DROP2",   t0: 67.53, t1: 77.13, color: "#f0792f" },
    { name: "OUTRO",   t0: 77.13, t1: 81.0,  color: "#7e57c2" },
  ],
};

const spec: Spec = {
  duration: 81,
  music: SHELTER_81_MUSIC,
  contacts,
  jitter: 0,
  axes: {
    // ── amplitude (the vertical lead): pop height of the airborne arc. Only a
    // long gap can pop, so it is HIGH on the sparse/float windows and near the
    // dense-beat cap (~0.1) through the 0.6 s grooves. Moderate on the floats —
    // maxing it makes the arc plunge and blows speed up.
    amplitude: keyframes([
      { t: 0, v: 0.40, ease: "smooth" },     // intro 1.2 s bounces
      { t: 5.14, v: 0.42, ease: "easeOut" },
      { t: 9.33, v: 0.42, ease: "smooth" },
      { t: 9.93, v: 0.08, ease: "smooth" },   // GROOVE: dense → near cap
      { t: 38.73, v: 0.10, ease: "smooth" },  // groove→verse→build all dense
      { t: 39.33, v: 0.82, ease: "easeOut" }, // CHORUS1 FLOAT (1.8 s) — the showpiece air under the vocal
      { t: 41.0, v: 0.82 },                    // hold high to the float's mid-gap sample
      { t: 41.13, v: 0.10, ease: "smooth" },   // float lands → dense close resumes (sharp drop)
      { t: 41.73, v: 0.10, ease: "easeOut" }, // chorus-1 close: dense again
      { t: 48.33, v: 0.12, ease: "hold" },    // CHORUS2: dense (impact carries the drama)
      { t: 57.93, v: 0.42, ease: "easeOut" }, // BREAKDOWN: calm 1.2 s bobs over the ambient dip
      { t: 61.54, v: 0.42, ease: "hold" },     // (the big showpiece airs live in chorus-1 + drop-2)
      { t: 66.34, v: 0.42, ease: "easeOut" },  // lift tightening into the drop
      { t: 67.53, v: 0.12, ease: "smooth" },   // DROP2: dense
      { t: 72.33, v: 0.12 },                    // hold dense low right up to the float launch
      { t: 72.34, v: 0.80, ease: "easeOut" },  // float 1 (1.8 s showpiece air)
      { t: 74.11, v: 0.80 },                    // float 2 launch
      { t: 75.9, v: 0.80 },                     // hold high to float 2's mid-gap sample
      { t: 75.94, v: 0.14, ease: "easeOut" },  // hard re-entry (dense)
      { t: 76.53, v: 0.14 },                    // (dense)
      { t: 77.13, v: 0.40, ease: "smooth" },   // OUTRO 1.2 s bounces
      { t: 81.0, v: 0.38 },
    ]),
    // ── air: airborne fraction. Rides with the energy — moderate/flowing in the
    // groove, aloft for the chorus, VERY high over the long breakdown gaps for
    // floaty release airs, eased back down to resolve.
    air: keyframes([
      { t: 0, v: 0.46, ease: "easeIn" },
      { t: 9.93, v: 0.55, ease: "smooth" },  // groove flowing
      { t: 19.53, v: 0.58, ease: "smooth" }, // verse
      { t: 29.13, v: 0.62, ease: "easeIn" }, // build rising
      { t: 38.73, v: 0.70, ease: "smooth" }, // chorus-1 rise
      { t: 41.13, v: 0.74, ease: "smooth" }, // float aloft
      { t: 48.33, v: 0.72, ease: "smooth" }, // chorus-2 aloft + fast
      { t: 57.93, v: 0.72, ease: "smooth" }, // breakdown: calm floaty bobs
      { t: 61.54, v: 0.74, ease: "hold" },
      { t: 67.53, v: 0.68, ease: "easeOut" }, // drop-2 dense
      { t: 72.34, v: 0.76, ease: "easeIn" },  // drop-2 float
      { t: 77.13, v: 0.60, ease: "easeOut" }, // outro
      { t: 81.0, v: 0.54 },
    ]),
    // ── speed: banks BEFORE each peak, eases in the breakdown so the long gaps
    // still carry. Peaks at chorus-2 (fast rider ⇒ high impact ceiling ⇒ the
    // hard slams are physically realizable).
    speed: keyframes([
      { t: 0, v: 0.36, ease: "easeIn" },     // intro: carry the slides
      { t: 9.93, v: 0.48, ease: "smooth" },
      { t: 19.53, v: 0.56, ease: "smooth" },
      { t: 29.13, v: 0.62, ease: "easeIn" }, // build: bank speed
      { t: 38.73, v: 0.74, ease: "smooth" }, // chorus-1 fast
      { t: 48.33, v: 0.80, ease: "smooth" }, // CHORUS-2 PEAK
      { t: 54.33, v: 0.80, ease: "hold" },
      { t: 57.93, v: 0.68, ease: "easeOut" },// breakdown: stay flowing (low speed ⇒ steep fall ⇒
      { t: 61.54, v: 0.64, ease: "hold" },   // hard catch; keep horizontal pace so the float lands soft)
      { t: 66.34, v: 0.60, ease: "easeIn" }, // lift
      { t: 67.53, v: 0.74, ease: "smooth" }, // drop-2
      { t: 72.34, v: 0.62, ease: "easeOut" },// mini-break
      { t: 76.53, v: 0.66, ease: "smooth" }, // re-entry
      { t: 77.13, v: 0.58, ease: "easeOut" },// outro
      { t: 81.0, v: 0.52 },
    ]),
  },
};

export default spec;
