/** End-to-end verification of shared-account review, native replay and audio. */
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {chromium} from 'playwright';
const arg=(k,d)=>process.argv.find(a=>a.startsWith(`--${k}=`))?.slice(k.length+3)??d;
const origin=arg('origin','http://localhost:8767'),source=arg('collection'),out=arg('out');
assert.ok(source&&out,'--collection=/generated/.../collection.json --out=DIR required');mkdirSync(out,{recursive:true});
const hash=b=>createHash('sha256').update(b).digest('hex'),bytes=readFileSync('.'+source),collection=JSON.parse(bytes);
assert.equal(hash(bytes),readFileSync('.'+source+'.sha256','utf8').trim());
const browser=await chromium.launch({headless:true,args:['--no-sandbox']}),errors=[],checks=[];
const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(60000);page.on('pageerror',e=>errors.push(e.message));
const ready=()=>page.waitForFunction(()=>!document.getElementById('play').disabled&&!document.getElementById('comparison').disabled);
const seek=async t=>page.locator('#seek').evaluate((e,t)=>{e.value=String(t);e.dispatchEvent(new Event('input'));},t);
const url=origin+'/motion-gallery/production.html?collection='+source+'&compare=previous';
try{
 await page.goto(url);await ready();assert.equal(await page.locator('#library button').count(),collection.entries.length);
 for(let i=0;i<collection.entries.length;i++){
  await page.locator('#library button').nth(i).click();await ready();
  const entry=collection.entries[i];assert.equal(await page.locator('#result-title').textContent(),`${entry.title} · seed ${entry.seed}`);
  await page.waitForFunction(()=>!document.getElementById('comparison-ride').hidden);
  assert.match(await page.locator('#production-metrics').textContent(),/Experimental impact quality/);
  assert.match(await page.locator('#reference-metrics').textContent(),/Experimental impact quality/);
  const manifest=JSON.parse(readFileSync('.'+entry.manifest)),cell=manifest.cells.find(c=>c.method==='production');
  const record=JSON.parse(readFileSync('.'+entry.manifest.replace(/manifest.json$/,cell.path)));
  assert.equal(await page.locator('#audio').getAttribute('data-sha256'),record.case.audioSha256);
  assert.equal(await page.locator('#contact-impact-review').isHidden(),false);
  assert.ok(await page.locator('#contact-impact-review tbody tr').count()>=record.impactEvaluation.targets.length);
  await seek(12);assert.equal(await page.locator('#time').textContent(),'12.00 s');
  await page.locator('#play').click();await page.waitForFunction(()=>document.getElementById('audio').currentTime>12.1);
  await page.locator('#play').click();assert.equal(await page.locator('#audio').evaluate(e=>e.paused),true);
  checks.push({song:entry.song,seed:entry.seed,nativeCurrentAndBaseline:true,sharedRuler:true,verifiedMusicPlays:true});
 }
 await page.locator('#contact-impact-review summary').click();
 const count=await page.locator('#contact-impact-review tbody tr').count();
 await page.locator('#contact-impact-review input').check();assert.ok(await page.locator('#contact-impact-review tbody tr').count()>=count);
 await page.locator('.contact-impact-chart svg').click({position:{x:350,y:65}});
 assert.equal(await page.locator('#audio').evaluate(e=>e.paused),true);
 await page.locator('#contact-impact-review tbody button').first().click();
 assert.ok(+(await page.locator('#seek').inputValue())<1);
 await seek(+(await page.locator('#seek').getAttribute('max')));await page.locator('#play').click();
 await page.waitForFunction(()=>document.getElementById('audio').currentTime>.1&&document.getElementById('audio').currentTime<2);
 await page.locator('#play').click();
 checks.push({chartAndRowsSeek:true,chartPauses:true,smallResponsesInspectable:true,restartFromEnd:true});
 await page.screenshot({path:out+'/native-desktop.png',fullPage:true});
 await page.evaluate(()=>{const b=document.querySelectorAll('#library button');b[0].click();b[2].click();b[b.length-1].click();});
 await ready();assert.equal(await page.locator('#result-title').textContent(),`${collection.entries.at(-1).title} · seed ${collection.entries.at(-1).seed}`);
 checks.push({rapidSelectionKeepsFinalTrackAndMeasurements:true});
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.screenshot({path:out+'/native-mobile.png',fullPage:true});checks.push({mobileOverflow:false});
 await page.goto(origin+'/motion-gallery/production.html');await ready();
 assert.equal(await page.locator('#contact-impact-review').isHidden(),true);
 assert.match(await page.locator('#production-metrics').textContent(),/Landing score/);checks.push({validatedDefaultUnaffected:true});
 const stale=await browser.newPage();stale.setDefaultTimeout(60000);stale.on('pageerror',e=>errors.push(e.message));
 await stale.route('**/*.mp3',async route=>{const response=await route.fetch(),body=Buffer.from(await response.body());body[0]^=1;await route.fulfill({response,body});});
 await stale.goto(url);await stale.waitForFunction(()=>document.getElementById('status').textContent.includes('does not match the saved recording'));
 assert.equal(await stale.locator('#play').isDisabled(),true);assert.equal(await stale.locator('#seek').isDisabled(),false);
 checks.push({changedAudioRejected:true,silentScrubbingStillAvailable:true});assert.deepEqual(errors,[]);
 const result={schema:'line.contact-impact-browser-checks.v1',collectionSha256:hash(bytes),scriptSha256:hash(readFileSync(import.meta.filename)),checks,errors};
 const body=JSON.stringify(result,null,2)+'\n';writeFileSync(out+'/browser.json',body);writeFileSync(out+'/browser.json.sha256',hash(body)+'\n');console.log(JSON.stringify(result));
}finally{await browser.close();}
