/**
 * The `ride()` composer.
 *
 * Walks a list of `Move`s in order, threading a single lr-core engine
 * through each move's `place()`. After all placements, runs the detector
 * once against the full cumulative track, then walks moves again calling
 * each `verify()` with the detection + move's frame range + owned line
 * ids. Bails (skipping remaining moves) on catastrophic failure.
 */

import {
  type Move,
  type MoveVerdict,
  type Placement,
} from "./moves.ts";
import { type TrackLine, type TrackJson } from "./primitive.ts";
import {
  detect,
  extractRawTrajectory,
  type Detection,
} from "./detector.ts";

// deno-lint-ignore no-explicit-any
const lrCore: any = await import("lr-core/line-rider-engine/index.js");
const LineRiderEngine = lrCore.default;
const { createLineFromJson } = lrCore;

export type MoveStep = {
  move: Move;
  placement: Placement | null;
  verdict: MoveVerdict | null;
  skipped: boolean;
  skipReason?: string;
};

export type RideResult = {
  track: TrackJson;
  detection: Detection;
  steps: MoveStep[];
  /** All moves placed + every verdict.passed AND no drift entries. */
  allPassed: boolean;
  /** terminus.reason === "endOfSpec". */
  survived: boolean;
};

export type RideOpts = {
  /** Padding frames after the last move's atFrame. */
  postFrames?: number;
  /** Override the spec duration (frames). Defaults to lastAtFrame + postFrames. */
  duration?: number;
  /** Track label (cosmetic). */
  label?: string;
};

export function ride(moves: Move[], opts: RideOpts = {}): RideResult {
  if (moves.length === 0) {
    throw new Error("ride: at least one move required");
  }

  // Sort by atFrame so the composer can walk in time order, regardless of
  // how the user listed them.
  const sorted = [...moves].sort((a, b) => a.atFrame - b.atFrame);

  const postFrames = opts.postFrames ?? 80;
  const duration = opts.duration ?? sorted[sorted.length - 1].atFrame + postFrames;

  const steps: MoveStep[] = sorted.map((m) => ({
    move: m,
    placement: null,
    verdict: null,
    skipped: false,
  }));

  // ── Place: walk moves, thread engine, accumulate lines ──
  // deno-lint-ignore no-explicit-any
  let engine: any = new LineRiderEngine();
  const accumulated: TrackLine[] = [];
  let nextLineId = 1;

  for (const step of steps) {
    try {
      const placement = step.move.place({
        engine,
        accumulated,
        lineIdStart: nextLineId,
        duration,
      });
      step.placement = placement;
      accumulated.push(...placement.lines);
      engine = placement.engineAfter;
      nextLineId += placement.lines.length;
    } catch (e) {
      step.skipped = true;
      step.skipReason = `place() threw: ${String(e)}`;
    }
  }

  // ── Simulate the full track once ──
  const raw = extractRawTrajectory(engine, duration);
  const det = detect(raw);

  // ── Verify each move ──
  for (const step of steps) {
    if (step.skipped || !step.placement) continue;
    const range = { start: step.move.atFrame, end: step.placement.endFrame };
    if (det.terminus.frame < range.start) {
      // Ride ended before this move's geometry was reached. Mark skipped.
      step.skipped = true;
      step.skipReason =
        `ride terminated (${det.terminus.reason} @ f=${det.terminus.frame}) before move's atFrame (${range.start})`;
      continue;
    }
    step.verdict = step.move.verify(det, range, step.placement.lineIds);
  }

  // ── Assemble track JSON ──
  const track: TrackJson = {
    label: opts.label ?? "ride",
    creator: "line",
    description: "Generated by ride()",
    duration,
    version: "6.2",
    audio: null,
    startPosition: { x: 0, y: 0 },
    riders: [
      { startPosition: { x: 0, y: 0 }, startVelocity: { x: 0.4, y: 0 }, remountable: 1 },
    ],
    layers: [
      { id: 0, type: 0, name: "Base Layer", visible: true, editable: true, folderId: -1 },
    ],
    script: "",
    lines: accumulated,
  };

  const survived = det.terminus.reason === "endOfSpec";
  const allPassed = steps.every(
    (s) => !s.skipped && s.verdict !== null && s.verdict.passed && s.verdict.drift.length === 0,
  );

  return {
    track,
    detection: det,
    steps,
    allPassed,
    survived,
  };
}

/** Pretty-print a ride summary to stdout. */
export function printRideReport(result: RideResult): void {
  console.log("");
  console.log(`Ride: ${result.steps.length} move${result.steps.length === 1 ? "" : "s"}, ${result.track.lines.length} lines, ${result.track.duration} frame spec`);
  console.log(`Survived: ${result.survived ? "yes" : "no"} (terminus ${result.detection.terminus.reason} @ ${result.detection.terminus.frame})`);
  console.log(`All passed: ${result.allPassed ? "yes" : "no"}`);
  const s = result.detection.summary;
  console.log(`Summary: ${(s.contactFractionSpec * 100).toFixed(1)}% sliding · longest slide ${s.longestContactRun}f (${(s.longestContactRun / 40).toFixed(2)}s) · mean vx sliding ${s.meanVxSliding.toFixed(2)}`);
  console.log("");
  console.log("step  type      at    end   passed  drift                                            observed");
  for (const step of result.steps) {
    const i = result.steps.indexOf(step) + 1;
    if (step.skipped) {
      console.log(
        `${String(i).padStart(4)}  ${step.move.type.padEnd(8)} ${String(step.move.atFrame).padStart(4)}    -   SKIP    ${(step.skipReason ?? "").slice(0, 80)}`,
      );
      continue;
    }
    const v = step.verdict;
    const placement = step.placement;
    const driftStr = v && v.drift.length > 0
      ? v.drift.map((d) => `${d.metric}: ${d.expected} got ${d.actual}`).join("; ")
      : "—";
    const obsStr = v
      ? Object.entries(v.observed).map(([k, val]) => `${k}=${val}`).slice(0, 4).join(" ")
      : "";
    console.log(
      `${String(i).padStart(4)}  ${step.move.type.padEnd(8)} ${String(step.move.atFrame).padStart(4)} ${String(placement?.endFrame ?? "-").padStart(4)}  ${(v?.passed ? "yes" : "no ").padEnd(7)} ${driftStr.slice(0, 47).padEnd(47)} ${obsStr}`,
    );
  }
  console.log("");
}
